apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: items-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hiver-hitesh/items-gitops.git
    targetRevision: HEAD
    path: charts/items-api
    helm:
      releaseName: app          # keep object names = app-items-api (matches manual install)
  destination:
    server: https://kubernetes.default.svc
    namespace: items
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
