apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-items-api
  labels:
    app: items-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: items-api
  ports:
  - name: http
    port: {{ .Values.service.port }}   # 80
    targetPort: http                    # → container port 8000
